#!/bin/bash
#
# Tenant Onboarding Script
# Usage: ./scripts/create-tenant.sh <slug> <db-name> <pg-host> <pg-port> <pg-user> <pg-password>
#
# Example:
#   ./scripts/create-tenant.sh ocean ocean_db localhost 5432 postgres mypassword
#
# What it does:
#   1. Creates a new PostgreSQL database
#   2. Runs Prisma migrations on the new database
#   3. Seeds default data (SystemSettings, EmailTemplates, SiteContent)
#   4. Generates an env template file for Dokploy
#
set -euo pipefail

SLUG="${1:?Usage: $0 <slug> <db-name> <pg-host> <pg-port> <pg-user> <pg-password>}"
DB_NAME="${2:?Missing db-name}"
PG_HOST="${3:-localhost}"
PG_PORT="${4:-5432}"
PG_USER="${5:-postgres}"
PG_PASS="${6:?Missing pg-password}"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

DATABASE_URL="postgresql://${PG_USER}:${PG_PASS}@${PG_HOST}:${PG_PORT}/${DB_NAME}?schema=public"

echo ""
echo "╔══════════════════════════════════════════════╗"
echo "║         TENANT ONBOARDING: ${SLUG}           "
echo "╚══════════════════════════════════════════════╝"
echo ""

# ── Step 1: Create database ──────────────────────────────────────────────────
echo "→ Creating database: ${DB_NAME}..."
PGPASSWORD="$PG_PASS" psql -h "$PG_HOST" -p "$PG_PORT" -U "$PG_USER" -d postgres -c "CREATE DATABASE \"${DB_NAME}\";" 2>/dev/null || {
  echo "  ⚠ Database already exists or creation failed — continuing..."
}

# ── Step 2: Run Prisma migrations ────────────────────────────────────────────
echo "→ Running Prisma migrations..."
cd "$PROJECT_DIR"
DATABASE_URL="$DATABASE_URL" npx prisma migrate deploy

# ── Step 3: Seed default data ────────────────────────────────────────────────
echo "→ Seeding default data..."
DATABASE_URL="$DATABASE_URL" npx tsx scripts/seed-tenant.ts "$SLUG"

# ── Step 4: Generate env template ────────────────────────────────────────────
ENV_FILE="$PROJECT_DIR/scripts/.env.${SLUG}"
SLUG_UPPER="$(echo "$SLUG" | tr '[:lower:]' '[:upper:]')"

cat > "$ENV_FILE" << EOF
# ── ${SLUG_UPPER} Tenant Environment ──
# Generated by create-tenant.sh on $(date +%Y-%m-%d)
# Copy these to your Dokploy project environment variables.

# Database
DATABASE_URL=${DATABASE_URL}

# Tenant identity
TENANT_ID=${SLUG}
NEXT_PUBLIC_SITE_NAME=${SLUG_UPPER}
NEXT_PUBLIC_SITE_FULL_NAME=THE ${SLUG_UPPER} LABEL
NEXTAUTH_URL=https://example.com
NEXTAUTH_SECRET=$(openssl rand -base64 32)

# Features (now managed from admin dashboard — these are initial fallbacks)
NEXT_PUBLIC_FEATURE_SUBMISSIONS=true
NEXT_PUBLIC_FEATURE_CONTRACTS=true
NEXT_PUBLIC_FEATURE_EARNINGS=true
NEXT_PUBLIC_FEATURE_PAYMENTS=true
NEXT_PUBLIC_FEATURE_RELEASES=true
NEXT_PUBLIC_FEATURE_COMMS=true
NEXT_PUBLIC_FEATURE_DISCORD=false
NEXT_PUBLIC_FEATURE_WISE=false
NEXT_PUBLIC_FEATURE_SPOTIFY_SYNC=true

# Optional: Control Panel DB (for centralized management)
# CONTROL_DB_URL=postgresql://...

# Optional: Mail
# SMTP_HOST=
# SMTP_PORT=
# SMTP_USER=
# SMTP_PASS=
# SMTP_FROM=

# Optional: Spotify API
# SPOTIFY_CLIENT_ID=
# SPOTIFY_CLIENT_SECRET=
EOF

echo ""
echo "✓ Tenant '${SLUG}' created successfully!"
echo "  Database: ${DATABASE_URL}"
echo "  Env file: ${ENV_FILE}"
echo ""
echo "Next steps:"
echo "  1. Update NEXTAUTH_URL in ${ENV_FILE} with the actual domain"
echo "  2. Copy env vars to Dokploy project"
echo "  3. Deploy from the repo"
echo "  4. Go to Admin → Settings → Features & Branding to customize"
echo ""
